// Sample questions seeded into the in-memory mock database (dev mode).
// These match the Question shape used across practice/exam/daily flows:
// options are a { A, B, C, D } map and correctAnswer is the option key.

export interface SeedQuestion {
  questionText: string;
  options: Record<string, string>;
  correctAnswer: string;
  explanation: string;
  subject: string;
  system: string;
  topic: string;
  subtopic?: string;
  qbankType?: string;
  universityTag?: string;
  examType?: string;
  difficulty: 'easy' | 'medium' | 'hard';
  tags?: string[];
  isFree: boolean;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  {
    questionText: 'A 45-year-old man presents with crushing retrosternal chest pain radiating to the left arm. ECG shows ST-segment elevation in leads II, III, and aVF. Which coronary artery is most likely occluded?',
    options: {
      A: 'Left anterior descending artery',
      B: 'Right coronary artery',
      C: 'Left circumflex artery',
      D: 'Left main coronary artery',
    },
    correctAnswer: 'B',
    explanation: 'Inferior wall MI (ST elevation in II, III, aVF) is most commonly caused by occlusion of the right coronary artery (RCA), which supplies the inferior wall of the heart.',
    subject: 'Medicine',
    system: 'Cardiovascular',
    topic: 'Ischemic Heart Disease',
    subtopic: 'Myocardial Infarction',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS Final Year',
    difficulty: 'medium',
    tags: ['cardiology', 'MI', 'ECG'],
    isFree: true,
  },
  {
    questionText: 'Which of the following is the rate-limiting enzyme of glycolysis?',
    options: {
      A: 'Hexokinase',
      B: 'Phosphofructokinase-1',
      C: 'Pyruvate kinase',
      D: 'Aldolase',
    },
    correctAnswer: 'B',
    explanation: 'Phosphofructokinase-1 (PFK-1) catalyzes the conversion of fructose-6-phosphate to fructose-1,6-bisphosphate and is the rate-limiting (committed) step of glycolysis. It is activated by AMP and fructose-2,6-bisphosphate, and inhibited by ATP and citrate.',
    subject: 'Biochemistry',
    system: 'Metabolism',
    topic: 'Carbohydrate Metabolism',
    subtopic: 'Glycolysis',
    qbankType: 'mbbs',
    universityTag: 'KEMU',
    examType: 'MBBS 1st Year',
    difficulty: 'easy',
    tags: ['biochem', 'glycolysis', 'enzymes'],
    isFree: true,
  },
  {
    questionText: 'A newborn has poor feeding, lethargy, and a musty odor to the urine. Which enzyme deficiency is most likely?',
    options: {
      A: 'Tyrosinase',
      B: 'Phenylalanine hydroxylase',
      C: 'Homogentisate oxidase',
      D: 'Branched-chain alpha-ketoacid dehydrogenase',
    },
    correctAnswer: 'B',
    explanation: 'Musty/urine odor, poor feeding, and lethargy in a newborn suggest phenylketonuria (PKU), caused by deficiency of phenylalanine hydroxylase. Early dietary restriction of phenylalanine prevents intellectual disability.',
    subject: 'Pediatrics',
    system: 'Metabolism',
    topic: 'Inborn Errors of Metabolism',
    subtopic: 'Phenylketonuria',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS 4th Year',
    difficulty: 'medium',
    tags: ['pediatrics', 'PKU', 'metabolism'],
    isFree: true,
  },
  {
    questionText: 'A 30-year-old woman with Graves disease is treated with propylthiouracil. Which adverse effect requires immediate discontinuation of the drug?',
    options: {
      A: 'Rash',
      B: 'Agranulocytosis',
      C: 'Nausea',
      D: 'Arthralgia',
    },
    correctAnswer: 'B',
    explanation: 'Agranulocytosis is a rare but life-threatening adverse effect of thionamides (propylthiouracil, methimazole). Patients must be warned to report sore throat or fever immediately, and the drug is stopped if neutrophil counts fall.',
    subject: 'Pharmacology',
    system: 'Endocrine',
    topic: 'Thyroid Disorders',
    subtopic: 'Antithyroid Drugs',
    qbankType: 'mbbs',
    universityTag: 'SZBML',
    examType: 'MBBS 3rd Year',
    difficulty: 'medium',
    tags: ['pharma', 'thyroid', 'PTU'],
    isFree: false,
  },
  {
    questionText: 'Which nerve injury results in wrist drop?',
    options: {
      A: 'Median nerve',
      B: 'Ulnar nerve',
      C: 'Radial nerve',
      D: 'Musculocutaneous nerve',
    },
    correctAnswer: 'C',
    explanation: 'The radial nerve innervates the extensor muscles of the forearm. Injury (e.g., midshaft humerus fracture) causes wrist drop due to loss of wrist and finger extension.',
    subject: 'Anatomy',
    system: 'Musculoskeletal',
    topic: 'Peripheral Nerves',
    subtopic: 'Upper Limb',
    qbankType: 'mbbs',
    universityTag: 'FJMU',
    examType: 'MBBS 1st Year',
    difficulty: 'easy',
    tags: ['anatomy', 'nerves', 'upper limb'],
    isFree: true,
  },
  {
    questionText: 'A 60-year-old smoker presents with a lung mass. Histology shows small blue cells with salt-and-pepper chromatin and crush artifact. Which is the most likely diagnosis?',
    options: {
      A: 'Adenocarcinoma',
      B: 'Squamous cell carcinoma',
      C: 'Small cell carcinoma',
      D: 'Large cell carcinoma',
    },
    correctAnswer: 'C',
    explanation: 'Small cell carcinoma of the lung shows sheets of small blue cells with scant cytoplasm, salt-and-pepper chromatin, and crush artifact. It is strongly associated with smoking and paraneoplastic syndromes such as SIADH.',
    subject: 'Pathology',
    system: 'Respiratory',
    topic: 'Lung Tumors',
    subtopic: 'Small Cell Carcinoma',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS 3rd Year',
    difficulty: 'hard',
    tags: ['pathology', 'lung', 'oncology'],
    isFree: false,
  },
  {
    questionText: 'Which of the following organisms is the most common cause of community-acquired pneumonia in adults?',
    options: {
      A: 'Mycoplasma pneumoniae',
      B: 'Streptococcus pneumoniae',
      C: 'Legionella pneumophila',
      D: 'Haemophilus influenzae',
    },
    correctAnswer: 'B',
    explanation: 'Streptococcus pneumoniae is the most common bacterial cause of community-acquired pneumonia in adults, classically producing lobar consolidation and rusty sputum.',
    subject: 'Microbiology',
    system: 'Respiratory',
    topic: 'Respiratory Infections',
    subtopic: 'Community-Acquired Pneumonia',
    qbankType: 'mbbs',
    universityTag: 'RMU',
    examType: 'MBBS 3rd Year',
    difficulty: 'easy',
    tags: ['micro', 'pneumonia', 'gram positive'],
    isFree: false,
  },
  {
    questionText: 'A 25-year-old woman has episodes of severe, unilateral, throbbing headache with nausea and photophobia lasting 6 hours. Which class of drugs is first-line for aborting an acute attack?',
    options: {
      A: 'NSAIDs',
      B: 'Triptans',
      C: 'Opioids',
      D: 'Benzodiazepines',
    },
    correctAnswer: 'B',
    explanation: 'Triptans (5-HT1B/1D agonists) are first-line abortive therapy for moderate-to-severe migraine attacks, acting by cranial vasoconstriction and inhibition of trigeminal nociception.',
    subject: 'Medicine',
    system: 'Neurology',
    topic: 'Headache',
    subtopic: 'Migraine',
    qbankType: 'usmle',
    examType: 'USMLE Step 2 CK',
    difficulty: 'medium',
    tags: ['neuro', 'migraine', 'triptans'],
    isFree: false,
  },
  {
    questionText: 'Which of the following best describes the function of surfactant in the lungs?',
    options: {
      A: 'Increases surface tension',
      B: 'Decreases surface tension',
      C: 'Increases alveolar compliance',
      D: 'Decreases alveolar surface area',
    },
    correctAnswer: 'B',
    explanation: 'Surfactant, produced by type II pneumocytes, lowers alveolar surface tension, preventing alveolar collapse at end-expiration. Deficiency causes neonatal respiratory distress syndrome (hyaline membrane disease).',
    subject: 'Physiology',
    system: 'Respiratory',
    topic: 'Pulmonary Function',
    subtopic: 'Surfactant',
    qbankType: 'mbbs',
    universityTag: 'KEMU',
    examType: 'MBBS 1st Year',
    difficulty: 'easy',
    tags: ['physio', 'surfactant', 'respiratory'],
    isFree: true,
  },
  {
    questionText: 'A 55-year-old man with chronic liver disease presents with ascites and confusion. Serum ammonia is elevated. Which of the following is the most appropriate first-line treatment?',
    options: {
      A: 'Lactulose',
      B: 'Spironolactone',
      C: 'Metronidazole',
      D: 'Rifaximin',
    },
    correctAnswer: 'A',
    explanation: 'Hepatic encephalopathy is treated with lactulose, which acidifies the colon, traps ammonia as ammonium, and promotes its excretion. It is first-line; rifaximin is an adjunct for recurrent episodes.',
    subject: 'Medicine',
    system: 'Gastrointestinal',
    topic: 'Liver Disease',
    subtopic: 'Hepatic Encephalopathy',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS Final Year',
    difficulty: 'medium',
    tags: ['GI', 'liver', 'encephalopathy'],
    isFree: false,
  },
  {
    questionText: 'Which tumor marker is most associated with colorectal cancer?',
    options: {
      A: 'AFP',
      B: 'CA 19-9',
      C: 'CEA',
      D: 'CA-125',
    },
    correctAnswer: 'C',
    explanation: 'Carcinoembryonic antigen (CEA) is the tumor marker most associated with colorectal cancer. It is used mainly for monitoring recurrence after resection rather than for screening.',
    subject: 'Medicine',
    system: 'Gastrointestinal',
    topic: 'Colorectal Cancer',
    subtopic: 'Tumor Markers',
    qbankType: 'usmle',
    examType: 'USMLE Step 2 CK',
    difficulty: 'easy',
    tags: ['oncology', 'CEA', 'colorectal'],
    isFree: false,
  },
  {
    questionText: 'A 28-year-old woman at 34 weeks gestation has preeclampsia with severe features. Which is the drug of choice for seizure prophylaxis?',
    options: {
      A: 'Magnesium sulfate',
      B: 'Diazepam',
      C: 'Phenytoin',
      D: 'Labetalol',
    },
    correctAnswer: 'A',
    explanation: 'Magnesium sulfate is the drug of choice for prevention and treatment of eclamptic seizures in preeclampsia. It is given as a loading dose followed by a maintenance infusion with monitoring of reflexes and urine output.',
    subject: 'Obstetrics',
    system: 'Reproductive',
    topic: 'Hypertensive Disorders of Pregnancy',
    subtopic: 'Preeclampsia',
    qbankType: 'fcps',
    examType: 'FCPS Part 1',
    difficulty: 'medium',
    tags: ['obgyn', 'preeclampsia', 'magnesium'],
    isFree: false,
  },
  {
    questionText: 'A child presents with acute-onset stridor, barking cough, and low-grade fever. Which is the most likely diagnosis?',
    options: {
      A: 'Epiglottitis',
      B: 'Croup',
      C: 'Bronchiolitis',
      D: 'Foreign body aspiration',
    },
    correctAnswer: 'B',
    explanation: 'Croup (laryngotracheobronchitis), most often caused by parainfluenza virus, presents with a barking seal-like cough, inspiratory stridor, and hoarseness, typically in children aged 6 months to 3 years.',
    subject: 'Pediatrics',
    system: 'Respiratory',
    topic: 'Upper Airway Infections',
    subtopic: 'Croup',
    qbankType: 'mbbs',
    universityTag: 'DUHS',
    examType: 'MBBS 4th Year',
    difficulty: 'easy',
    tags: ['pediatrics', 'croup', 'stridor'],
    isFree: false,
  },
  {
    questionText: 'Which of the following antibiotics inhibits bacterial protein synthesis by binding to the 30S ribosomal subunit?',
    options: {
      A: 'Penicillin',
      B: 'Vancomycin',
      C: 'Tetracycline',
      D: 'Erythromycin',
    },
    correctAnswer: 'C',
    explanation: 'Tetracyclines bind the 30S ribosomal subunit and inhibit aminoacyl-tRNA binding, blocking bacterial protein synthesis. Macrolides (e.g., erythromycin) bind the 50S subunit instead.',
    subject: 'Pharmacology',
    system: 'Infectious Disease',
    topic: 'Antibiotics',
    subtopic: 'Protein Synthesis Inhibitors',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS 3rd Year',
    difficulty: 'easy',
    tags: ['pharma', 'antibiotics', '30S'],
    isFree: false,
  },
  {
    questionText: 'A 70-year-old man has difficulty initiating urination and a distended bladder. Digital rectal exam reveals an enlarged, firm prostate. Which test is most appropriate for initial evaluation?',
    options: {
      A: 'Prostate biopsy',
      B: 'Serum PSA with digital rectal exam',
      C: 'Bone scan',
      D: 'CT abdomen',
    },
    correctAnswer: 'B',
    explanation: 'For suspected BPH or prostate cancer, initial evaluation includes serum PSA and digital rectal examination. Prostate biopsy is reserved for patients with elevated PSA or suspicious DRE findings.',
    subject: 'Surgery',
    system: 'Urology',
    topic: 'Prostate Disease',
    subtopic: 'Benign Prostatic Hyperplasia',
    qbankType: 'fcps',
    examType: 'FCPS Part 1',
    difficulty: 'medium',
    tags: ['urology', 'PSA', 'BPH'],
    isFree: false,
  },
  {
    questionText: 'Which immunoglobulin crosses the placenta and provides passive immunity to the fetus?',
    options: {
      A: 'IgA',
      B: 'IgM',
      C: 'IgG',
      D: 'IgE',
    },
    correctAnswer: 'C',
    explanation: 'IgG is the only immunoglobulin that crosses the placenta (via FcRn receptors), providing passive humoral immunity to the newborn. IgM does not cross the placenta, so its presence in cord blood suggests congenital infection.',
    subject: 'Immunology',
    system: 'Immune System',
    topic: 'Immunoglobulins',
    subtopic: 'Passive Immunity',
    qbankType: 'mbbs',
    universityTag: 'SZBML',
    examType: 'MBBS 2nd Year',
    difficulty: 'easy',
    tags: ['immunology', 'IgG', 'placenta'],
    isFree: true,
  },
  {
    questionText: 'A 40-year-old woman has weight gain, moon facies, buffalo hump, and abdominal striae. Cortisol is elevated and not suppressed by dexamethasone. Which is the most likely diagnosis?',
    options: {
      A: 'Addison disease',
      B: 'Cushing syndrome',
      C: 'Primary aldosteronism',
      D: 'Pheochromocytoma',
    },
    correctAnswer: 'B',
    explanation: 'The constellation of central obesity, moon facies, buffalo hump, and striae suggests Cushing syndrome from cortisol excess. Failure of cortisol suppression with dexamethasone confirms the diagnosis.',
    subject: 'Medicine',
    system: 'Endocrine',
    topic: 'Adrenal Disorders',
    subtopic: 'Cushing Syndrome',
    qbankType: 'usmle',
    examType: 'USMLE Step 1',
    difficulty: 'hard',
    tags: ['endocrine', 'cortisol', 'cushing'],
    isFree: false,
  },
  {
    questionText: 'Which ECG finding is most characteristic of hyperkalemia?',
    options: {
      A: 'Prolonged QT interval',
      B: 'Peaked T waves',
      C: 'ST-segment depression',
      D: 'U waves',
    },
    correctAnswer: 'B',
    explanation: 'Hyperkalemia classically produces tall, peaked (tented) T waves, followed by widening of the QRS complex and loss of P waves as severity increases. Emergency treatment includes calcium gluconate, insulin-glucose, and dialysis.',
    subject: 'Medicine',
    system: 'Cardiovascular',
    topic: 'Electrolyte Disorders',
    subtopic: 'Hyperkalemia',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS Final Year',
    difficulty: 'easy',
    tags: ['ECG', 'hyperkalemia', 'electrolytes'],
    isFree: true,
  },
  {
    questionText: 'A 35-year-old man with a proximal humerus fracture develops difficulty abducting the arm. Which nerve is most likely injured?',
    options: {
      A: 'Axillary nerve',
      B: 'Radial nerve',
      C: 'Median nerve',
      D: 'Long thoracic nerve',
    },
    correctAnswer: 'A',
    explanation: 'The axillary nerve (C5-C6) innervates the deltoid and teres minor. It is injured in proximal humerus fractures or anterior shoulder dislocations, causing loss of shoulder abduction and deltoid atrophy.',
    subject: 'Anatomy',
    system: 'Musculoskeletal',
    topic: 'Peripheral Nerves',
    subtopic: 'Shoulder',
    qbankType: 'mbbs',
    universityTag: 'KEMU',
    examType: 'MBBS 1st Year',
    difficulty: 'medium',
    tags: ['anatomy', 'axillary nerve', 'shoulder'],
    isFree: false,
  },
  {
    questionText: 'A 50-year-old alcoholic presents with acute severe epigastric pain radiating to the back. Serum amylase and lipase are markedly elevated. What is the most likely diagnosis?',
    options: {
      A: 'Peptic ulcer perforation',
      B: 'Acute pancreatitis',
      C: 'Cholecystitis',
      D: 'Mesenteric ischemia',
    },
    correctAnswer: 'B',
    explanation: 'Acute pancreatitis presents with severe epigastric pain radiating to the back, often after alcohol excess or gallstones. Elevated serum amylase and lipase (lipase more specific) confirm the diagnosis.',
    subject: 'Surgery',
    system: 'Gastrointestinal',
    topic: 'Pancreatic Disease',
    subtopic: 'Acute Pancreatitis',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS Final Year',
    difficulty: 'medium',
    tags: ['surgery', 'pancreatitis', 'amylase'],
    isFree: false,
  },
  {
    questionText: 'Which organism is the most common cause of urinary tract infections?',
    options: {
      A: 'Klebsiella pneumoniae',
      B: 'Proteus mirabilis',
      C: 'Escherichia coli',
      D: 'Enterococcus faecalis',
    },
    correctAnswer: 'C',
    explanation: 'Escherichia coli is responsible for about 80-90% of community-acquired UTIs. It is a gram-negative rod that colonizes the perineum and ascends the urethra to cause cystitis and pyelonephritis.',
    subject: 'Microbiology',
    system: 'Renal',
    topic: 'Urinary Tract Infections',
    subtopic: 'Cystitis',
    qbankType: 'mbbs',
    universityTag: 'RMU',
    examType: 'MBBS 3rd Year',
    difficulty: 'easy',
    tags: ['micro', 'UTI', 'e coli'],
    isFree: false,
  },
  {
    questionText: 'A 22-year-old college student presents with fever, sore throat, fatigue, and posterior cervical lymphadenopathy. Peripheral smear shows atypical lymphocytes. Which test is most specific for the diagnosis?',
    options: {
      A: 'Heterophile antibody test',
      B: 'Throat culture',
      C: 'CBC with differential',
      D: 'Liver function tests',
    },
    correctAnswer: 'A',
    explanation: 'Infectious mononucleosis from Epstein-Barr virus presents with fever, exudative pharyngitis, posterior cervical lymphadenopathy, and atypical lymphocytes. The heterophile (Monospot) antibody test is specific and confirms the diagnosis.',
    subject: 'Medicine',
    system: 'Hematology',
    topic: 'Infectious Mononucleosis',
    subtopic: 'EBV',
    qbankType: 'usmle',
    examType: 'USMLE Step 2 CK',
    difficulty: 'medium',
    tags: ['EBV', 'monospot', 'hematology'],
    isFree: false,
  },
  {
    questionText: 'Which vitamin deficiency causes Wernicke encephalopathy, characterized by ataxia, ophthalmoplegia, and confusion?',
    options: {
      A: 'Vitamin B12',
      B: 'Vitamin B1 (Thiamine)',
      C: 'Vitamin B6',
      D: 'Vitamin C',
    },
    correctAnswer: 'B',
    explanation: 'Thiamine (vitamin B1) deficiency causes Wernicke encephalopathy (ataxia, ophthalmoplegia, confusion), classically in alcoholics. Treatment is IV thiamine, given BEFORE glucose to prevent precipitation of Korsakoff syndrome.',
    subject: 'Biochemistry',
    system: 'Neurology',
    topic: 'Vitamin Deficiencies',
    subtopic: 'Thiamine',
    qbankType: 'mbbs',
    universityTag: 'UHS',
    examType: 'MBBS 2nd Year',
    difficulty: 'medium',
    tags: ['vitamins', 'thiamine', 'wernicke'],
    isFree: true,
  },
];
